import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard, Target, Users, UserRound, Clock3, FlaskConical, Search, ArrowUpRight, Activity, ChevronRight} from 'lucide-react';
import './styles.css';

const model = {batch:'2026-08-01', users:2381, churners:363, prevalence:15.25, prAuc:39.70, rocAuc:78.31, cIndex:76.17};
const top = {10:{selected:239, found:118, precision:49.37, recall:32.51, f1:39.20},20:{selected:477, found:189, precision:39.62, recall:52.07, f1:44.17}};
const segments = [
  {name:'솔로랭크·활동 많음', count:852, churn:12.1, risk:0.31, action:'랭크 미션 / 시즌 콘텐츠'},
  {name:'솔로랭크·활동 감소', count:641, churn:24.8, risk:0.47, action:'복귀 캠페인 / 플레이 리마인드'},
  {name:'자유랭크 중심', count:522, churn:17.4, risk:0.36, action:'친구 파티·협동 이벤트'},
  {name:'일반·캐주얼 중심', count:327, churn:10.8, risk:0.27, action:'신규 모드·콘텐츠 추천'},
  {name:'칼바람 중심', count:39, churn:15.4, risk:0.33, action:'표본 작음 — 탐색용'}
];
const customers = [
  ['4 / 233ea11270a56d7f','솔로랭크·활동 감소',0.91,12,3,16.6,'복귀 캠페인'],
  ['3 / c4bbda1b9c7fb014','자유랭크 중심',0.86,9,4,8.2,'친구 파티 이벤트'],
  ['2 / 25ca007debf92212','일반·캐주얼 중심',0.82,5,1,12.4,'콘텐츠 추천'],
  ['2 / d64959903d661250','솔로랭크·활동 감소',0.79,7,2,10.1,'복귀 캠페인'],
  ['1 / 00851b6d3a490dc8','솔로랭크·활동 많음',0.74,22,18,1.4,'관찰'],
  ['4 / 388fec8ebdaefb1a','자유랭크 중심',0.69,11,7,4.3,'저비용 알림']
];

function Metric({label,value,sub,accent}){return <div className="metric"><span>{label}</span><strong className={accent?'accent':''}>{value}</strong><small>{sub}</small></div>}
function Bar({value,color='#4f7cff'}){return <div className="bar"><i style={{width:`${Math.min(value,100)}%`,background:color}}/></div>}
function Gauge({value}){return <div className="gauge"><div className="gauge-inner"><b>{Math.round(value*100)}%</b><span>이탈 위험</span></div></div>}

function Overview(){return <>
  <div className="page-head"><div><p className="eyebrow">BATCH MONITORING · ESTABLISHED ACTIVE USERS</p><h1>이탈 예측 운영 현황</h1><p className="muted">기준일 {model.batch} · 최근 30일 활동 고객을 대상으로 한 운영용 요약</p></div><button className="ghost">배치 변경 <ChevronRight size={15}/></button></div>
  <div className="metrics"><Metric label="진성 활동 고객" value={model.users.toLocaleString()} sub="games_prev30d ≥ 4, games_30d > 0"/><Metric label="실제 30일 이탈률" value={`${model.prevalence}%`} sub={`${model.churners}명 / ${model.users.toLocaleString()}명`} /><Metric label="PR-AUC (AP)" value={`${model.prAuc}%`} sub="불균형 데이터 핵심 지표" accent/><Metric label="ROC-AUC" value={`${model.rocAuc}%`} sub="순위 분리 성능"/></div>
  <div className="grid two"><section className="card"><div className="card-title"><div><h2>조치 규모별 성능</h2><p className="muted">위험 점수 상위 고객을 몇 %까지 조치할지 비교</p></div><Target size={20}/></div><div className="compare-row"><div><b>상위 10%</b><Bar value={top[10].recall}/><span>Recall {top[10].recall}% · Precision {top[10].precision}%</span></div><div><b>상위 20%</b><Bar value={top[20].recall} color="#23b26d"/><span>Recall {top[20].recall}% · Precision {top[20].precision}%</span></div></div></section><section className="card"><div className="card-title"><div><h2>운영 권장안</h2><p className="muted">예산과 고객 경험을 함께 고려한 기본값</p></div><Activity size={20}/></div><div className="recommend"><strong>상위 20% · 저비용 개입</strong><p>477명을 대상으로 189명의 실제 이탈자를 포착했습니다. 알림·콘텐츠 추천부터 시작하고, 고비용 보상은 상위 10%로 좁히는 방식이 적절합니다.</p></div></section></div>
  <section className="card"><div className="card-title"><div><h2>모델 상태</h2><p className="muted">실제 운영 후보와 탐색 실험을 분리해 표시합니다.</p></div><FlaskConical size={20}/></div><div className="model-grid"><div><span className="status-dot green"/>CatBoost · 운영 후보<strong>5-fold / class weight 비교 완료</strong></div><div><span className="status-dot amber"/>ROS·SMOTE · 비교 실험<strong>PR-AUC 개선 폭 제한적</strong></div><div><span className="status-dot slate"/>Transformer · churn 주모델 제외<strong>행동 시퀀스 분석용으로 보류</strong></div><div><span className="status-dot purple"/>Survival · synthetic demo<strong>실제 장기 로그 확보 전 참고용</strong></div></div></section>
 </>}

function Campaign(){const [pct,setPct]=useState(20); const d=top[pct]; return <><div className="page-head"><div><p className="eyebrow">ACTION DESIGN</p><h1>Campaign Planner</h1><p className="muted">예산과 개입 강도에 맞춰 위험 고객 범위를 선택합니다.</p></div></div><section className="card planner"><div className="planner-top"><div><span>조치 대상 비율</span><strong>{pct}%</strong></div><div className="pill">{d.selected.toLocaleString()}명 선택</div></div><input type="range" min="10" max="20" step="10" value={pct} onChange={e=>setPct(Number(e.target.value))}/><div className="scale"><span>10% · 고비용 보상</span><span>20% · 저비용 알림/추천</span></div><div className="metrics compact"><Metric label="찾은 이탈자" value={`${d.found}명`} sub={`Recall ${d.recall}%`}/><Metric label="헛짚은 고객" value={`${d.selected-d.found}명`} sub={`Precision ${d.precision}%`}/><Metric label="F1" value={d.f1.toFixed(2)} sub="Precision·Recall 균형"/></div><div className="recommend"><strong>{pct===10?'고객당 비용이 큰 보상·상담':'푸시·콘텐츠 추천·이벤트 노출'}에 적합</strong><p>{pct===10?'대상을 좁혀 헛짚는 비용을 줄입니다.':'더 많은 이탈자를 찾지만 비이탈 고객도 포함됩니다.'}</p></div></section></>}

function Segments(){return <><div className="page-head"><div><p className="eyebrow">CUSTOMER SEGMENTATION</p><h1>Segment Analysis</h1><p className="muted">진성고객 안에서 플레이 유형과 활동 변화를 분리합니다.</p></div></div><section className="card table-card"><table><thead><tr><th>세그먼트</th><th>고객 수</th><th>관측 이탈률</th><th>평균 위험도</th><th>권장 액션</th></tr></thead><tbody>{segments.map(s=><tr key={s.name}><td><b>{s.name}</b></td><td>{s.count.toLocaleString()}명</td><td><Bar value={s.churn*2.5} color={s.churn>20?'#ef6a6a':'#4f7cff'}/><span>{s.churn}%</span></td><td>{s.risk.toFixed(2)}</td><td><span className="tag">{s.action}</span></td></tr>)}</tbody></table></section><div className="notice">칼바람 중심 세그먼트는 39명으로 표본이 작아 정책 판단보다 탐색용으로만 사용합니다.</div></>}

function RiskCustomers(){const [q,setQ]=useState(''); const rows=customers.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())||x[1].includes(q)); return <><div className="page-head"><div><p className="eyebrow">ACTION QUEUE</p><h1>Risk Customers</h1><p className="muted">개별 고객은 캠페인 실행 후보를 확인하는 용도로만 사용합니다.</p></div><div className="search"><Search size={16}/><input placeholder="ID 또는 세그먼트 검색" value={q} onChange={e=>setQ(e.target.value)}/></div></div><section className="card table-card"><table><thead><tr><th>고객 식별자</th><th>세그먼트</th><th>위험 점수</th><th>최근 30일</th><th>이전 30일</th><th>마지막 경기 후</th><th>권장 액션</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b className="mono">{r[0]}</b></td><td>{r[1]}</td><td><strong className={r[2]>.8?'danger':''}>{r[2].toFixed(2)}</strong></td><td>{r[3]}경기</td><td>{r[4]}경기</td><td>{r[5]}일</td><td><span className="tag">{r[6]}</span></td></tr>)}</tbody></table></section></>}

function Detail(){return <><div className="page-head"><div><p className="eyebrow">EXPLAINABILITY</p><h1>Customer Detail</h1><p className="muted">선택된 고객의 점수와 관측된 행동 변화를 설명합니다.</p></div></div><div className="grid two"><section className="card detail-hero"><div><span className="muted">고객</span><h2 className="mono">4 / 233ea11270a56d7f</h2><span className="tag">솔로랭크·활동 감소</span></div><Gauge value={0.91}/></section><section className="card"><div className="card-title"><h2>행동 근거</h2><Activity size={20}/></div><div className="reason"><div><span>최근 5경기 승률</span><b>20%</b><small>이전 5경기 60% 대비 하락</small></div><div><span>최근 경기 간격</span><b>3.2일</b><small>이전 평균 0.5일 대비 증가</small></div><div><span>마지막 활동</span><b>16.6일 전</b><small>기준일 2026-08-01</small></div></div></section></div><section className="card"><div className="card-title"><h2>해석 주의</h2></div><p className="muted">위험 점수는 모델의 순위 점수이며 계정 탈퇴 확률로 단정하지 않습니다. 행동 변화는 관측 신호이고 원인·보상 효과는 별도 A/B 테스트가 필요합니다.</p></section></>}

function Timing(){return <><div className="page-head"><div><p className="eyebrow">TIMING DEMO</p><h1>Timing Simulation</h1><p className="muted">합성 survival 모델로 개입 시점 개념을 보여주는 데모입니다.</p></div><span className="warning">SYNTHETIC DEMO</span></div><div className="metrics"><Metric label="7일 생존" value="82%" sub="30일 무경기 상태에 아직 도달하지 않을 확률"/><Metric label="14일 생존" value="64%" sub="합성 예측 예시"/><Metric label="30일 생존" value="41%" sub="실제 운영값 아님"/><Metric label="Concordance" value="0.762" sub="합성 test split"/></div><section className="card"><div className="card-title"><h2>개입 타이밍 예시</h2><Clock3 size={20}/></div><div className="timeline"><div><b>0일</b><span>활동 정상</span></div><div className="active"><b>7일</b><span>저비용 알림</span></div><div className="active"><b>14일</b><span>콘텐츠 추천</span></div><div className="risk"><b>30일</b><span>휴면 전환 후보</span></div></div><p className="muted footnote">현재 데이터에는 실제 장기 생존 정답이 없으므로 운영 모델로 사용하지 않고, 향후 장기 로그가 확보되면 재학습해야 합니다.</p></section></>}

function Lab(){const rows=[['CatBoost · baseline','0.397','32.5%','운영 후보'],['CatBoost · class weight 2','0.398','32.2%','개선 미미'],['ROS','0.396','31.9%','비교 완료'],['SMOTE','0.391','30.8%','비교 완료'],['Transformer churn','0.236','—','주모델 제외'],['Survival Cox · synthetic','—','—','탐색 데모']];return <><div className="page-head"><div><p className="eyebrow">EXPERIMENT REGISTRY</p><h1>Model Lab</h1><p className="muted">발표와 운영에서 실험 결과를 재현할 수 있도록 기록합니다.</p></div></div><section className="card table-card"><table><thead><tr><th>모델·처리</th><th>PR-AUC</th><th>Recall@10%</th><th>상태</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td><span className="tag">{r[3]}</span></td></tr>)}</tbody></table></section><section className="card"><h2>채택 원칙</h2><p className="muted">CatBoost는 진성 활동 고객의 30일 이탈 위험 순위에 사용합니다. Transformer와 survival은 현재 라벨·관찰기간 한계 때문에 보조 분석/향후 확장으로 분리합니다.</p></section></>}

const nav=[['overview','Overview',LayoutDashboard],['campaign','Campaign Planner',Target],['segments','Segment Analysis',Users],['risk','Risk Customers',UserRound],['detail','Customer Detail',UserRound],['timing','Timing Simulation',Clock3],['lab','Model Lab',FlaskConical]];
function App(){const [page,setPage]=useState('overview'); const C={overview:Overview,campaign:Campaign,segments:Segments,risk:RiskCustomers,detail:Detail,timing:Timing,lab:Lab}[page]; return <div className="app"><aside><div className="brand"><div className="brand-mark">L</div><div><b>LoL Churn</b><span>INTELLIGENCE</span></div></div><div className="batch"><span>분석 배치</span><b>2026-08-01</b><small>진성 활동 고객 · {model.users.toLocaleString()}명</small></div><nav>{nav.map(([id,label,Icon])=><button className={page===id?'selected':''} onClick={()=>setPage(id)} key={id}><Icon size={17}/><span>{label}</span>{page===id&&<ArrowUpRight size={14}/>}</button>)}</nav><div className="side-note"><span className="status-dot green"/> 모델 상태<br/><small>CatBoost 운영 후보</small></div></aside><main><div className="topbar"><span>Customer Retention Workspace</span><span className="live"><i/> Batch ready</span></div><div className="content"><C/></div><footer>Internal decision support · 점수는 순위 기반이며 인과관계를 의미하지 않습니다.</footer></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
